### PR TITLE
added reset to analytics methods

### PR DESCRIPTION
**Pull request by evanpaschke**
Resolves https://github.com/vvo/analytics.js-loader/issues/4

### CODE REVIEW

**Comment by vvo** [comment]
Thanks, giving you push access since I am not a heavy user of this module. Please be nice and use PR/semver :)

**Comment by vvo** [comment]
What's your npm username @evanpaschke?

**Comment by evanpaschke** [comment]
Cool, thanks! I'm evanpaschke on npm.

**Comment by vvo** [comment]
ok done

**Pull request merged**
